SELECT load_extension('mod_spatialite');

SELECT InitSpatialMetaData('NONE');
SELECT InsertEpsgSrid(25829);
SELECT InsertEpsgSrid(25830);
SELECT InsertEpsgSrid(25831);
SELECT InsertEpsgSrid(4258);
SELECT InsertEpsgSrid(4326);
SELECT InsertEpsgSrid(3857);

CREATE TABLE "AGRZONA" (
"PK_UID" INTEGER PRIMARY KEY AUTOINCREMENT,
"C_PROVINCIA" INTEGER,
"C_MUNICIPIO" INTEGER,
"C_AGREGADO" INTEGER,
"C_ZONA" INTEGER );

CREATE TABLE "MUNICIPIOS"( "PK_UID" INTEGER PRIMARY KEY AUTOINCREMENT,
"C_PROVINCIA" INTEGER,
"C_MUNICIPIO" INTEGER,
"C_PROVMUN" TEXT,
"D_NOMBRE" TEXT,
"C_PROVMUNINE" TEXT,
Geometry MULTIPOLYGON );

SELECT RecoverGeometryColumn("MUNICIPIOS", "Geometry", 25830, "MULTIPOLYGON", 2);
SELECT CreateSpatialIndex("MUNICIPIOS" , "Geometry");

CREATE TABLE "PROVINCIAS" (
"PK_UID" INTEGER PRIMARY KEY AUTOINCREMENT,
"C_PROVINCIA" INTEGER,
"D_NOMBRE" VARCHAR(15),
"GEOMETRY" MULTIPOLYGON );

SELECT RecoverGeometryColumn("PROVINCIAS", "Geometry", 25830, "MULTIPOLYGON", 2);
SELECT CreateSpatialIndex("PROVINCIAS" , "Geometry");

CREATE TABLE "RECINTOS" ( "PK_UID" INTEGER PRIMARY KEY ASC,
"C_PROVINCIA" INTEGER,
"C_MUNICIPIO" INTEGER,
"C_AGREGADO" INTEGER,
"C_ZONA" INTEGER,
"C_POLIGONO" INTEGER,
"C_PARCELA" INTEGER,
"C_RECINTO" INTEGER,
"C_USO_SIGPAC" TEXT,
"C_COEF_REGADIO" INTEGER,
"C_REFREC" TEXT,
"L_SUP_SIGPAC" DOUBLE,
"C_REFPAR" TEXT );

SELECT AddGeometryColumn('RECINTOS', 'Geometry', 25830, 'MULTIPOLYGON', 2);
SELECT RecoverGeometryColumn('RECINTOS', 'Geometry', 25830, "MULTIPOLYGON", 2);
